import { db } from '@/lib/firebase';
import { collection, addDoc, Timestamp } from 'firebase/firestore';
import { Post } from '@/app/types/post';

const programs = [
  // Child Protection Programs
  {
    title: "Safe Spaces Initiative",
    content: "A comprehensive program dedicated to creating safe environments for children at risk of abuse and neglect.",
    category: "child-protection",
    excerpt: "Protecting children through community-based interventions and support systems.",
    coverImage: "/images/child-protection-1.jpg",
    published: true,
    tags: ["programs", "child-protection"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: true,
  },
  {
    title: "Child Rights Guardianship",
    content: "Empowering local communities to recognize, report, and prevent child abuse and exploitation.",
    category: "child-protection",
    excerpt: "Community-led approach to child protection and welfare.",
    coverImage: "/images/child-protection-2.jpg",
    published: true,
    tags: ["programs", "child-protection"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: false,
  },
  {
    title: "School Safety Network",
    content: "Implementing comprehensive safety protocols and awareness programs in schools to protect children from various forms of abuse.",
    category: "child-protection",
    excerpt: "Creating safer learning environments for children.",
    coverImage: "/images/child-protection-3.jpg",
    published: true,
    tags: ["programs", "child-protection"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: false,
  },
  {
    title: "Digital Child Protection",
    content: "Innovative program addressing online safety, cyberbullying, and digital threats facing children in the modern world.",
    category: "child-protection",
    excerpt: "Protecting children in the digital age.",
    coverImage: "/images/child-protection-4.jpg",
    published: true,
    tags: ["programs", "child-protection"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: true,
  },

  // Youth Empowerment Programs
  {
    title: "Leadership Development Program",
    content: "Comprehensive program to develop leadership skills, critical thinking, and personal development for youth.",
    category: "youth-empowerment",
    excerpt: "Nurturing the next generation of community leaders and changemakers.",
    coverImage: "/images/youth-empowerment-1.jpg",
    published: true,
    tags: ["programs", "youth-empowerment"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: true,
  },
  {
    title: "Skills for Success",
    content: "Vocational training and entrepreneurship program to equip youth with practical skills for economic independence.",
    category: "youth-empowerment",
    excerpt: "Empowering youth through practical skills and economic opportunities.",
    coverImage: "/images/youth-empowerment-2.jpg",
    published: true,
    tags: ["programs", "youth-empowerment"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: false,
  },
  {
    title: "Youth Innovation Hub",
    content: "A creative space providing technology training, mentorship, and innovation support for young entrepreneurs.",
    category: "youth-empowerment",
    excerpt: "Fostering creativity and technological skills among youth.",
    coverImage: "/images/youth-empowerment-3.jpg",
    published: true,
    tags: ["programs", "youth-empowerment"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: false,
  },
  {
    title: "Global Youth Exchange",
    content: "International program connecting youth from different cultures to promote global understanding and leadership.",
    category: "youth-empowerment",
    excerpt: "Building global citizenship and cross-cultural understanding.",
    coverImage: "/images/youth-empowerment-4.jpg",
    published: true,
    tags: ["programs", "youth-empowerment"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: true,
  },

  // Advocacy Programs
  {
    title: "Child Rights Advocacy Network",
    content: "A strategic network focused on policy change and public awareness about children's rights.",
    category: "advocacy",
    excerpt: "Amplifying children's voices through policy advocacy and public engagement.",
    coverImage: "/images/advocacy-1.jpg",
    published: true,
    tags: ["programs", "advocacy"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: true,
  },
  {
    title: "Media and Awareness Campaign",
    content: "Using media platforms to raise awareness about critical issues affecting children and youth.",
    category: "advocacy",
    excerpt: "Leveraging media to create social change and awareness.",
    coverImage: "/images/advocacy-2.jpg",
    published: true,
    tags: ["programs", "advocacy"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: false,
  },
  {
    title: "Legal Support for Children",
    content: "Providing legal aid and representation for children facing systemic challenges and rights violations.",
    category: "advocacy",
    excerpt: "Ensuring legal protection and justice for children.",
    coverImage: "/images/advocacy-3.jpg",
    published: true,
    tags: ["programs", "advocacy"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: false,
  },
  {
    title: "Policy Reform Initiative",
    content: "Comprehensive program working with government bodies to develop and implement child-friendly policies.",
    category: "advocacy",
    excerpt: "Driving systemic change through strategic policy advocacy.",
    coverImage: "/images/advocacy-4.jpg",
    published: true,
    tags: ["programs", "advocacy"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: true,
  },

  // Humanitarian Response Programs
  {
    title: "Emergency Child Support",
    content: "Rapid response program providing immediate support to children in crisis situations and disaster-affected areas.",
    category: "humanitarian-response",
    excerpt: "Swift and compassionate support for children in emergency situations.",
    coverImage: "/images/humanitarian-response-1.jpg",
    published: true,
    tags: ["programs", "humanitarian-response"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: true,
  },
  {
    title: "Resilience and Recovery",
    content: "Long-term support program helping children and communities recover and rebuild after humanitarian crises.",
    category: "humanitarian-response",
    excerpt: "Comprehensive support for healing and rebuilding after humanitarian challenges.",
    coverImage: "/images/humanitarian-response-2.jpg",
    published: true,
    tags: ["programs", "humanitarian-response"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: false,
  },
  {
    title: "Nutrition and Health Emergency Response",
    content: "Targeted intervention providing critical nutrition, medical care, and health support in humanitarian crisis zones.",
    category: "humanitarian-response",
    excerpt: "Addressing immediate health and nutritional needs in crisis situations.",
    coverImage: "/images/humanitarian-response-3.jpg",
    published: true,
    tags: ["programs", "humanitarian-response"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: false,
  },
  {
    title: "Refugee Children Support",
    content: "Comprehensive program providing education, psychological support, and integration assistance for refugee children.",
    category: "humanitarian-response",
    excerpt: "Supporting the most vulnerable children displaced by conflict and crisis.",
    coverImage: "/images/humanitarian-response-4.jpg",
    published: true,
    tags: ["programs", "humanitarian-response"],
    authorEmail: "admin@fsce.org",
    authorId: "admin",
    date: new Date().toISOString(),
    featured: true,
  }
];

async function seedPrograms() {
  const programsCollection = collection(db, 'posts');

  for (const program of programs) {
    try {
      const docRef = await addDoc(programsCollection, {
        ...program,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
        slug: program.title.toLowerCase().replace(/\s+/g, '-')
      });
      console.log(`Seeded program: ${program.title} with ID: ${docRef.id}`);
    } catch (error) {
      console.error(`Error seeding program ${program.title}:`, error);
    }
  }
}

seedPrograms().then(() => console.log('Seeding complete'));
